### ISSUE TITLE
Docker - ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by venkat091929** [Kong/mockbin#77]
I have same problem with Docker, could not able to create a bin. Get the below error. I have tried updated docker file with node version but no use ( followed this https://github.com/Kong/mockbin/issues/62)

ReferenceError: Promise is not defined
   at validator (/usr/src/app/node_modules/har-validator/lib/promise.js:42:14)
   at Object.response (/usr/src/app/node_modules/har-validator/lib/promise.js:110:10)
   at Object.module.exports (/usr/src/app/lib/routes/bins/create.js:46:12)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at IncomingMessage.<anonymous> (/usr/src/app/lib/middleware/body-parser.js:52:9)
   at IncomingMessage.emit (events.js:92:17)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:458:13)

**Comment by venkat091929** [comment]
Any updates/suggestions please?

**Comment by Neirda24** [comment]
Hi. Have the same problem. Created a simple `docker-compose.yml` file
```yml
version: '3.5'
services:
    redis:
        image: 'redis:3.2'
    mockbin:
        image: 'mashape/mockbin'
        ports:
          - '8080:8080'
```
but it doesn't seems to be working
